INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Angel','Angel Beats!','Kana','Hanazawa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Yuzu Otonashi','Angel Beats!','Hiroshi','Kamiya');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Yuri Nakamura','Angel Beats!','Harumi','Sakurai');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Hinata Hideki','Angel Beats!','Ryohei','Kimura');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Mikasa Ackerman','Attack on Titan','Yui','Ishikawa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Eren Yeager','Attack on Titan','Yuki','Kaji');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Armin Arlert','Attack on Titan','Marina','Inoue');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Rhint Celonias','Cowboy Bebop','Kappei','Yamaguchi');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('L','Death Note','Kappei','Yamaguchi');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Light','Death Note','Mamoru','Miyano');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Death the Kid','Soul Eater','Mamoru','Miyano');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Biba Amatori','Kabaneri of the Iron Fortress','Mamoru','Miyano');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Ryuk','Death Note','Shidou','Nakamura');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Near','Death Note','Noriko','Hidaka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Halle Lidner','Death Note','Akeno','Watanabe');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Liz Thompson','Soul Eater','Akeno','Watanabe');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Patty Thompson','Soul Eater','Narumi','Takahima');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Mumei','Kabaneri of the Iron Fortress','Sayaka', 'Senbongi');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Ikoma','Kabaneri of the Iron Fortress','Tasuku','Hatanaka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Lelouch Lamperouge','Code Geass: Lelouch of the Rebellion','Jun','Fukuyama');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Suzaku Kururugi','Code Geass: Lelouch of the Rebellion','Takahiro','Sakurai');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('C.C.','Code Geass: Lelouch of the Rebellion','Yukana','Nogami');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Yumi Azusa','Soul Eater','Yukana','Nogami');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Kallen Stadtfeld','Code Geass: Lelouch of the Rebellion','Ami','Koshimizu');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Maka Albarn','Soul Eater','Chiaki','Omigawa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Soul Evans','Soul Eater','Koki','Uchiyama');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Black Star','Soul Eater','Yumiko','Kobayashi');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Oyama','Angel Beats!','Yumiko','Kobayashi');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Nunnally Lamperouge','Code Geass: Lelouch of the Rebellion','Kaori','Nazuka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Tsubaki Nakatsukasa','Soul Eater','Kaori','Nazuka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Spike Spiegel','Cowboy Bebop','Koichi', 'Yamadera');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Ein','Cowboy Bebop','Koichi', 'Yamadera');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Jet Black','Cowboy Bebop','Unsho','Ishizuka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Mr. Leonhardt','Attack on Titan','Unsho','Ishizuka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Faye Valentine','Cowboy Bebop','Megumi','Hayashibara');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Edward Wong Hau Pepelu Tivrusky IV','Cowboy Bebop','Aoi','Tada');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Sora','No Game No Life','Yoshitsugu','Matsuoka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Shiro','No Game No Life','Ai','Kayano');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Stephanie Dola','No Game No Life','Yoko','Hikasa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Saitama','One Punch Man','Makoto','Furukawa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Genos','One Punch Man','Kaito','Ishikawa');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Koko Hekmatyr','Jormungand','Unsho','Ishizuka');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Lehm Brick','Jormungand','Shizuka','Itou');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Jonathan Mar','Jormungand','Mutsumi','Tamura');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Sofia Valmet','Jormungand','Sayaka','Ohara');
INSERT INTO CHARACTER(CharacterName,AnimeIn,VoiceActorFname,VoiceActorLname) VALUES ('Kasper Hekmatyr','Jormungand','Masaya','Matsukaze');
